version: '3.2'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: cadastro
    ports:
      - "5436:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
